// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgDt4eUZzyjsHc_OsI0B239obvbbz8ERc',
    appId: '1:845553516025:web:fb135f54312c2c1f4ed128',
    messagingSenderId: '845553516025',
    projectId: 'carryon-delivery-tracker',
    authDomain: 'carryon-delivery-tracker.firebaseapp.com',
    storageBucket: 'carryon-delivery-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlt8LjWlrS-vVtzcf7c4H9QMAof1-3JI0',
    appId: '1:845553516025:android:2f3098343ea510e04ed128',
    messagingSenderId: '845553516025',
    projectId: 'carryon-delivery-tracker',
    storageBucket: 'carryon-delivery-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbX3YQ9dDkJ5AprXNGQy50FE2vfwWGOdI',
    appId: '1:845553516025:ios:d126eabbf2cdd3b24ed128',
    messagingSenderId: '845553516025',
    projectId: 'carryon-delivery-tracker',
    storageBucket: 'carryon-delivery-tracker.firebasestorage.app',
    iosBundleId: 'com.developerruhban.carryon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbX3YQ9dDkJ5AprXNGQy50FE2vfwWGOdI',
    appId: '1:845553516025:ios:b3d2a5b0545959da4ed128',
    messagingSenderId: '845553516025',
    projectId: 'carryon-delivery-tracker',
    storageBucket: 'carryon-delivery-tracker.firebasestorage.app',
    iosBundleId: 'com.example.deliveryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgDt4eUZzyjsHc_OsI0B239obvbbz8ERc',
    appId: '1:845553516025:web:79acf1b0fbd9e28b4ed128',
    messagingSenderId: '845553516025',
    projectId: 'carryon-delivery-tracker',
    authDomain: 'carryon-delivery-tracker.firebaseapp.com',
    storageBucket: 'carryon-delivery-tracker.firebasestorage.app',
  );
}
